### ISSUE TITLE
dedicated screenshot server

### ISSUE THREAD

**Issue by micahstubbs** [micahstubbs/screenshot-service#9]
spin up a server that runs a headless browser to take screenshots

(and perhaps generate pdfs as well 🤔 )

## features
- [x] setup server 
- [x] set script to create a screenshot from a url
- [x] pick example to screenshot https://bl.ocks.org/micahstubbs/raw/3e931f7b5876254d7156a85cdd286f7b/
- [x] set up API server to  receive requests and respond with screenshots
- [x] cache screenshots in gcp bucket (persistent, faster than generating each request)
- [x] auth for API

## future work 
- upgrade auth to use jwt token https://github.com/micahstubbs/screenshot-service/issues/10
- cache in redis (ephemeral, faster than reading from gcp bucket probably) speed up screenshot serving from cache https://github.com/micahstubbs/screenshot-service/issues/11
- generate a pdf https://github.com/micahstubbs/screenshot-service/issues/13

**Comment by curran** [comment]
Some snippets that may be useful (from the thumbnail generation of datavis.tech):

```js
const setThumbnail = require('../../db/actions/setThumbnail')
const generateThumbnailBuffer = require('./generateThumbnailBuffer')

module.exports = async (browser, sandbox, shareDbDoc) => {
  const html = await sandbox({id: shareDbDoc.id})
  const page = await browser.newPage()
  const thumbnailBuffer = await generateThumbnailBuffer(page, html)
  const thumbnail = thumbnailBuffer.toString('base64')
  setThumbnail(shareDbDoc, thumbnail)
}
```

```js
const sharp = require('sharp')

module.exports = async generateThumbnailBuffer(page, html) => {
  await page.setViewport({width: 960, height: 500})
  await page.setContent(html)
  await page.waitFor(5000)

  const buffer = await page.screenshot()
  await page.close()

  return sharp(buffer)
    .resize(230, 120)
    .toBuffer()
}
```

```js
const browser = await puppeteer.launch({args: ['--no-sandbox']})
```

**Comment by micahstubbs** [comment]
TIL about the npm package https://www.npmjs.com/package/sharp

> The typical use case for this high speed Node.js module is to convert large images in common formats to smaller, web-friendly JPEG, PNG and WebP images of varying dimensions.

> Resizing an image is typically 4x-5x faster than using the quickest ImageMagick and GraphicsMagick settings.

thanks @curran 🙌

**Comment by micahstubbs** [comment]
some comments on setting headers for pdf files https://spin.atomicobject.com/2015/10/03/remote-pfs-node-js-express/

**Comment by micahstubbs** [comment]
# cache screenshots

following this guide to write files to a gcp bucket https://blog.datawheel.us/uploading-to-google-cloud-storage-from-node-js-bcdee76f83bc

**Comment by micahstubbs** [comment]
# cache in redis

thinking about what I want to cache in redis. 

some options:

- the whole image.  could be memory intensive
- the gcp bucket address of the image
- the local filesystem location of the image


🤔
